version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build-prod
  post_build:
    commands:
      - aws s3 sync ./dist s3://about-myself-web-devops --acl 'public-read' --delete
cache:
  paths:
    - ./node_modules