version: 0.2

phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run build release
artifacts:
  files:
    - dist/**/*
  name: about-myself-$(date +%Y-%m-%d)
cache:
  paths:
    - node_modules