version: 0.2

phases:
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build-prod
  post_build:
    commands:
      - echo Post build phase!
artifacts:
  files:
    - '**/*'
  discard-paths: yes
  base-directory: 'dist'
cache:
  paths:
    - ./node_modules