name: Feature branch build

on:
  push:
    branches:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DEFAULT_BRANCH: master
  AWS_HOSTING_S3_BUCKET: "about-myself-hosting"
  AWS_AUTH_ROLE: "arn:aws:iam::026090449790:role/gha-aws-oidc-oidbc-prod-ghaawsoidcroleprodADA66B76-16JXA65ME5F0Z"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Prepare variables
        run: echo SAFE_SOURCE_NAME=$(echo "${{ github.ref_name }}" | sed -r 's/[/.@_]+/-/g') >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install runtime
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm

      - name: Install
        run: npm ci

      - name: Checks
        run: npm run type-check

      - name: Build random branch
        if: env.SAFE_SOURCE_NAME != 'main'
        run: |
          npm run build-prod

      - name: Build main branch
        if: env.SAFE_SOURCE_NAME == 'main'
        run: |
          npm run build-release

      - name: Pre-render
        run: |
          npm run pre-render

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-west-1
          role-to-assume: ${{ env.AWS_AUTH_ROLE }}

      - name: Publish web-app to S3
        run: aws s3 sync ./dist s3://${{ env.AWS_HOSTING_S3_BUCKET }}/${{ env.SAFE_SOURCE_NAME }} --delete